### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by Unlimitosu** [mupq/pqriscv-vexriscv#6]
I cloned the repository and I tried to build it,  but an error occurred and I could not solve it.

Here is the log.

```
unlimit@ubuntu:~/Downloads/pqriscv-vexriscv$ sbt
[info] welcome to sbt 1.5.5 (Private Build Java 1.8.0_382)
[info] loading settings for project pqriscv-vexriscv-build from plugins.sbt ...
[info] loading project definition from /home/unlimit/Downloads/pqriscv-vexriscv/project
[info] loading settings for project pqvexriscv from build.sbt ...
Cloning into '/home/unlimit/.sbt/1.0/staging/dbf5d177968279a7a3c6/vexriscv'...
fatal: unable to connect to github.com:
github.com[0: 20.200.245.247]: errno=Connection refused

java.lang.RuntimeException: Nonzero exit code (128): git clone git://github.com/SpinalHDL/VexRiscv /home/unlimit/.sbt/1.0/staging/dbf5d177968279a7a3c6/vexriscv
	at scala.sys.package$.error(package.scala:30)
	at sbt.Resolvers$.run(Resolvers.scala:142)
	at sbt.Resolvers$.run(Resolvers.scala:133)
	at sbt.Resolvers$.$anonfun$git$3(Resolvers.scala:91)
	at sbt.Resolvers$.creates(Resolvers.scala:148)
	at sbt.Resolvers$.$anonfun$git$2(Resolvers.scala:90)
	at sbt.internal.BuildLoader$.$anonfun$componentLoader$2(BuildLoader.scala:177)
	at scala.Option.map(Option.scala:230)
	at sbt.internal.BuildLoader$.$anonfun$componentLoader$1(BuildLoader.scala:176)
	at sbt.internal.MultiHandler.apply(BuildLoader.scala:33)
	at sbt.internal.BuildLoader.apply(BuildLoader.scala:244)
	at sbt.internal.Load$.loadURI$1(Load.scala:549)
	at sbt.internal.Load$.loadAll(Load.scala:565)
	at sbt.internal.Load$.loadURI(Load.scala:495)
	at sbt.internal.Load$.load(Load.scala:474)
	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:243)
	at sbt.internal.Load$.timed(Load.scala:1393)
	at sbt.internal.Load$.apply(Load.scala:243)
	at sbt.internal.Load$.defaultLoad(Load.scala:56)
	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:959)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:959)
	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:912)
	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
	at sbt.Command$.process(Command.scala:189)
	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
	at scala.Option.getOrElse(Option.scala:189)
	at sbt.MainLoop$.process$1(MainLoop.scala:245)
	at sbt.MainLoop$.processCommand(MainLoop.scala:278)
	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:163)
	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
	at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:163)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.MainLoop$.next(MainLoop.scala:163)
	at sbt.MainLoop$.run(MainLoop.scala:144)
	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:119)
	at sbt.io.Using.apply(Using.scala:27)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:112)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:66)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:51)
	at sbt.MainLoop$.runLogged(MainLoop.scala:42)
	at sbt.StandardMain$.runManaged(Main.scala:218)
	at sbt.xMain$.$anonfun$run$11(Main.scala:133)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withIn(Console.scala:230)
	at sbt.internal.util.Terminal$.withIn(Terminal.scala:569)
	at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:350)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:559)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withErr(Console.scala:196)
	at sbt.internal.util.Terminal$.withOut(Terminal.scala:559)
	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:350)
	at sbt.xMain$.withStreams$1(Main.scala:87)
	at sbt.xMain$.run(Main.scala:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:56)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
[error] Nonzero exit code (128): git clone git://github.com/SpinalHDL/VexRiscv /home/unlimit/.sbt/1.0/staging/dbf5d177968279a7a3c6/vexriscv
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
[warn] Ignoring load failure: no project loaded.
java.lang.RuntimeException: Session not initialized.
	at scala.sys.package$.error(package.scala:30)
	at sbt.Project$.$anonfun$getOrError$1(Project.scala:450)
	at scala.Option.getOrElse(Option.scala:189)
	at sbt.Project$.getOrError(Project.scala:450)
	at sbt.Project$.session(Project.scala:456)
	at sbt.Project$.extract(Project.scala:461)
	at sbt.BuiltinCommands$.notifyUsersAboutShell(Main.scala:1179)
	at sbt.BuiltinCommands$.$anonfun$notifyUsersAboutShell$3(Main.scala:1188)
	at sbt.Command$.$anonfun$command$2(Command.scala:97)
	at sbt.Command$.process(Command.scala:189)
	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
	at scala.Option.getOrElse(Option.scala:189)
	at sbt.MainLoop$.process$1(MainLoop.scala:245)
	at sbt.MainLoop$.processCommand(MainLoop.scala:278)
	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:163)
	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
	at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:163)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.MainLoop$.next(MainLoop.scala:163)
	at sbt.MainLoop$.run(MainLoop.scala:144)
	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:119)
	at sbt.io.Using.apply(Using.scala:27)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:112)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:66)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:51)
	at sbt.MainLoop$.runLogged(MainLoop.scala:42)
	at sbt.StandardMain$.runManaged(Main.scala:218)
	at sbt.xMain$.$anonfun$run$11(Main.scala:133)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withIn(Console.scala:230)
	at sbt.internal.util.Terminal$.withIn(Terminal.scala:569)
	at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:350)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:559)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withErr(Console.scala:196)
	at sbt.internal.util.Terminal$.withOut(Terminal.scala:559)
	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:350)
	at sbt.xMain$.withStreams$1(Main.scala:87)
	at sbt.xMain$.run(Main.scala:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:56)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
[error] Session not initialized.
[error] Use 'last' for the full log.
```

I use Java JDK 1.8.0_382 and sbt script version 1.9.3.
It seems something wrong during the connection to the github repository, but I don't know the exact cause of this issue.

Here is a log when I use 'last' option. 
```
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
[debug] > Exec(early(addDefaultCommands), None, None)
[debug] > Exec(addDefaultCommands, None, None)
[debug] > Exec(early(initialize), None, None)
[debug] > Exec(initialize, None, None)
[debug] > Exec(boot, None, None)
[debug] > Exec(writeSbtVersion, None, None)
[debug] > Exec(reload, None, None)
[debug] > Exec(sbtStashOnFailure, None, None)
[debug] > Exec(onFailure loadFailed, None, None)
[debug] > Exec(loadp, None, None)
[info] welcome to sbt 1.5.5 (Private Build Java 1.8.0_382)
[debug] Load.defaultLoad until apply took 241.655581ms
[debug]           Load.loadUnit: plugins took 61.581984ms
[debug]           Load.loadUnit: defsScala took 0.159679ms
[debug] [Loading] Scanning directory /home/unlimit/Downloads/pqriscv-vexriscv/project
[debug]             Load.loadUnit: mkEval took 3.645489ms
[debug] [Loading] Found non-root projects 
[debug] [Loading] Done in /home/unlimit/Downloads/pqriscv-vexriscv/project, returning: ()
[debug] deducing auto plugins based on known facts Set(Atom(sbt.plugins.CorePlugin)) and clauses Clauses(Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.IvyPlugin)))
[debug] Clause(Atom(sbt.ScriptedPlugin),Set(Atom(sbt.plugins.JvmPlugin)))
[debug] Clause(Atom(sbt.plugins.SbtPlugin),Set(Atom(sbt.ScriptedPlugin)))
[debug] Clause(Atom(sbt.plugins.SemanticdbPlugin),Set(Atom(sbt.plugins.JvmPlugin)))
[debug] Clause(Atom(sbt.plugins.JUnitXmlReportPlugin),Set(Atom(sbt.plugins.JvmPlugin)))
[debug] Clause(Atom(sbt.plugins.MiniDependencyTreePlugin),Set(Atom(sbt.plugins.JvmPlugin)))
[debug] Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.IvyPlugin)))
[debug] Clause(Atom(sbt.plugins.IvyPlugin),Set(Atom(sbt.plugins.JvmPlugin)))
[debug] Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.SemanticdbPlugin)))
[debug] Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.JUnitXmlReportPlugin)))
[debug] Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.Giter8TemplatePlugin)))
[debug] Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.MiniDependencyTreePlugin))))
[debug]   :: deduced result: Matched(sbt.plugins.CorePlugin,sbt.plugins.Giter8TemplatePlugin,sbt.plugins.IvyPlugin,sbt.plugins.JvmPlugin,sbt.plugins.MiniDependencyTreePlugin,sbt.plugins.JUnitXmlReportPlugin,sbt.plugins.SemanticdbPlugin)
[debug] Plugins.deducer#function took 9.329019 ms
[info] loading settings for project pqriscv-vexriscv-build from plugins.sbt ...
[debug]               Load.resolveProject(pqriscv-vexriscv-build) took 23.097755ms
[debug]             Load.loadTransitive: finalizeProject(Project(id pqriscv-vexriscv-build, base: /home/unlimit/Downloads/pqriscv-vexriscv/project, plugins: List(<none>))) took 46.463112ms
[debug] [Loading] Done in /home/unlimit/Downloads/pqriscv-vexriscv/project, returning: (pqriscv-vexriscv-build)
[debug]           Load.loadUnit: loadedProjectsRaw took 433.732599ms
[debug]           Load.loadUnit: cleanEvalClasses took 4.463779ms
[debug]         Load.loadUnit(file:/home/unlimit/Downloads/pqriscv-vexriscv/project/, ...) took 503.211454ms
[debug]       Load.apply: load took 571.958281ms
[debug]       Load.apply: resolveProjects took 2.551509ms
[debug]       Load.apply: finalTransforms took 37.761446ms
[debug]       Load.apply: config.delegates took 4.280361ms
[debug]       Load.apply: Def.make(settings)... took 276.349569ms
[debug]       Load.apply: structureIndex took 35.462953ms
[debug]       Load.apply: mkStreams took 0.825694ms
[info] loading project definition from /home/unlimit/Downloads/pqriscv-vexriscv/project
[debug] Running task... Cancel: Signal, check cycles: false, forcegc: true
[debug]     Load.loadUnit: plugins took 1563.361275ms
[debug]     Load.loadUnit: defsScala took 0.002624ms
[debug] [Loading] Scanning directory /home/unlimit/Downloads/pqriscv-vexriscv
[debug]       Load.loadUnit: mkEval took 0.387326ms
[debug] [Loading] Found root project pqvexriscv w/ remaining 
[debug] deducing auto plugins based on known facts Set(Atom(sbt.plugins.CorePlugin)) and clauses Clauses(Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.IvyPlugin)))
[debug] Clause(Atom(sbt.ScriptedPlugin),Set(Atom(sbt.plugins.JvmPlugin)))
[debug] Clause(Atom(sbt.plugins.SbtPlugin),Set(Atom(sbt.ScriptedPlugin)))
[debug] Clause(Atom(sbt.plugins.SemanticdbPlugin),Set(Atom(sbt.plugins.JvmPlugin)))
[debug] Clause(Atom(sbt.plugins.JUnitXmlReportPlugin),Set(Atom(sbt.plugins.JvmPlugin)))
[debug] Clause(Atom(sbt.plugins.MiniDependencyTreePlugin),Set(Atom(sbt.plugins.JvmPlugin)))
[debug] Clause(Atom(org.scalafmt.sbt.ScalafmtPlugin),Set(Atom(sbt.plugins.JvmPlugin)))
[debug] Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.IvyPlugin)))
[debug] Clause(Atom(sbt.plugins.IvyPlugin),Set(Atom(sbt.plugins.JvmPlugin)))
[debug] Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.SemanticdbPlugin)))
[debug] Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.JUnitXmlReportPlugin)))
[debug] Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.Giter8TemplatePlugin)))
[debug] Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.MiniDependencyTreePlugin)))
[debug] Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(org.scalafmt.sbt.ScalafmtPlugin))))
[debug]   :: deduced result: Matched(sbt.plugins.CorePlugin,sbt.plugins.Giter8TemplatePlugin,sbt.plugins.IvyPlugin,sbt.plugins.JvmPlugin,org.scalafmt.sbt.ScalafmtPlugin,sbt.plugins.MiniDependencyTreePlugin,sbt.plugins.JUnitXmlReportPlugin,sbt.plugins.SemanticdbPlugin)
[debug] Plugins.deducer#function took 0.892096 ms
[info] loading settings for project pqvexriscv from build.sbt ...
[debug]         Load.resolveProject(pqvexriscv) took 3.331071ms
[debug]       Load.loadTransitive: finalizeProject(Project(id pqvexriscv, base: /home/unlimit/Downloads/pqriscv-vexriscv, dependencies: List(ClasspathDependency(RootProject(git://github.com/SpinalHDL/VexRiscv#5fc4125763a1b66758c387c0abea32e602b2e4e5),None)), plugins: List(<none>))) took 4.711681ms
[debug] [Loading] Done in /home/unlimit/Downloads/pqriscv-vexriscv, returning: (pqvexriscv)
[debug]     Load.loadUnit: loadedProjectsRaw took 35.588619ms
[debug]     Load.loadUnit: cleanEvalClasses took 0.505724ms
[debug]   Load.loadUnit(file:/home/unlimit/Downloads/pqriscv-vexriscv/, ...) took 1600.074306ms
[error] java.lang.RuntimeException: Nonzero exit code (128): git clone git://github.com/SpinalHDL/VexRiscv /home/unlimit/.sbt/1.0/staging/dbf5d177968279a7a3c6/vexriscv
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.Resolvers$.run(Resolvers.scala:142)
[error] 	at sbt.Resolvers$.run(Resolvers.scala:133)
[error] 	at sbt.Resolvers$.$anonfun$git$3(Resolvers.scala:91)
[error] 	at sbt.Resolvers$.creates(Resolvers.scala:148)
[error] 	at sbt.Resolvers$.$anonfun$git$2(Resolvers.scala:90)
[error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$2(BuildLoader.scala:177)
[error] 	at scala.Option.map(Option.scala:230)
[error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$1(BuildLoader.scala:176)
[error] 	at sbt.internal.MultiHandler.apply(BuildLoader.scala:33)
[error] 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:244)
[error] 	at sbt.internal.Load$.loadURI$1(Load.scala:549)
[error] 	at sbt.internal.Load$.loadAll(Load.scala:565)
[error] 	at sbt.internal.Load$.loadURI(Load.scala:495)
[error] 	at sbt.internal.Load$.load(Load.scala:474)
[error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:243)
[error] 	at sbt.internal.Load$.timed(Load.scala:1393)
[error] 	at sbt.internal.Load$.apply(Load.scala:243)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:56)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:959)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:959)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:912)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
[error] 	at sbt.Command$.process(Command.scala:189)
[error] 	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
[error] 	at scala.Option.getOrElse(Option.scala:189)
[error] 	at sbt.MainLoop$.process$1(MainLoop.scala:245)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:278)
[error] 	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:163)
[error] 	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
[error] 	at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
[error] 	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:163)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:163)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:144)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:119)
[error] 	at sbt.io.Using.apply(Using.scala:27)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:112)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:66)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:51)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:42)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:218)
[error] 	at sbt.xMain$.$anonfun$run$11(Main.scala:133)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at scala.Console$.withIn(Console.scala:230)
[error] 	at sbt.internal.util.Terminal$.withIn(Terminal.scala:569)
[error] 	at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:350)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at scala.Console$.withOut(Console.scala:167)
[error] 	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:559)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at scala.Console$.withErr(Console.scala:196)
[error] 	at sbt.internal.util.Terminal$.withOut(Terminal.scala:559)
[error] 	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:350)
[error] 	at sbt.xMain$.withStreams$1(Main.scala:87)
[error] 	at sbt.xMain$.run(Main.scala:121)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:56)
[error] 	at sbt.xMain.run(Main.scala:46)
[error] 	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:149)
[error] 	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:159)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:44)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:21)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
[error] 	at xsbt.boot.Boot$.run(Boot.scala:73)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:21)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] Nonzero exit code (128): git clone git://github.com/SpinalHDL/VexRiscv /home/unlimit/.sbt/1.0/staging/dbf5d177968279a7a3c6/vexriscv
[error] Use 'last' for the full log.
[debug] > Exec(loadFailed, None, None)
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
[debug] > Exec(last, None, None)
```

How can I solve it?

**Comment by rpls** [comment]
Sorry for the long delay, I finally have the time now to maintain this project again.

It should be fixed now, the URL format of the VexRiscv dependency was broken (for newer SBT files).
